### ISSUE TITLE
<FIX> fix typing and grammatical errors in README.md

### ISSUE THREAD

**Issue by rover07** [Grow-with-Open-Source/Notebook#7]
![Screenshot from 2023-10-27 19-27-23](https://github.com/Grow-with-Open-Source/Notebook/assets/95951482/f93b7336-5238-4abf-bf83-25486be136cb)
Assign me this issue as I'm trying for hacktoberfest and will be a good start for me.

**Comment by iamwatchdogs** [comment]
Thank you for your raising the issue and fixing the typos. I'll add the `hacktoberfest-accepted` label as soon as the PR#8 has been merged.
